<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="user-PC" name="com.sarkarijobs.test.CannedSearch" tests="6" failures="1" timestamp="4 Aug 2016 10:25:28 GMT" time="14.884" errors="0">
  <testcase name="popularJobsByState" time="14.881" classname="com.sarkarijobs.test.CannedSearch">
    <failure type="java.lang.AssertionError" message="expected [158] but found [618]">
      <![CDATA[java.lang.AssertionError: expected [158] but found [618]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at com.sarkarijobs.test.CannedSearch.popularJobsByState(CannedSearch.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:648)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:834)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1176)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1101)
	at org.testng.TestNG.run(TestNG.java:1009)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
    </failure>
  </testcase> <!-- popularJobsByState -->
  <testcase name="testPopularCategory" time="0.000" classname="com.sarkarijobs.test.CannedSearch"/>
  <testcase name="testTrendingCarousel" time="0.001" classname="com.sarkarijobs.test.CannedSearch"/>
  <testcase name="testRecentCarousel" time="0.001" classname="com.sarkarijobs.test.CannedSearch"/>
  <testcase name="testSidebarByJobs" time="0.000" classname="com.sarkarijobs.test.CannedSearch"/>
  <testcase name="testSidebarByLocation" time="0.001" classname="com.sarkarijobs.test.CannedSearch"/>
</testsuite> <!-- com.sarkarijobs.test.CannedSearch -->
